apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp-pod
  template:
   metadata:
    labels:
     app: myjavaapp-pod
   spec:
    containers:
    - name: myjabaapp-container
      image: maha4iac/mahaonlinestore:1
      ports:
      - containerPort: 8080
