apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp-pod
    version: 2.7.2
  template:
   metadata:
    labels:
     app: myjavaapp-pod
     version: 2.7.2
   spec:
    containers:
    - name: myjabaapp-container
      image: maha4iac/mahaonlinestore:2
      ports:
      - containerPort: 8080
