apiVersion: v1
kind: Service
metadata:
 name: myjavaapp-svc
 labels:
    app: myjavaapp-pod
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
     app:  myjavaapp-pod

