apiVersion: extensions/v1
kind: Ingress
metadata:
  name: myweb-ingress
  namespace: default
  
spec:
  rules:
  - http:
      paths:
        - path: /muna
          backend:
            serviceName: mywebsiteone-svc
            servicePort: 8080
        - path: /abhi
          backend:
            serviceName: mywebsitetwo-svc
            servicePort: 8080