apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: web-srv
              servicePort: 8080
          - path: /v2
            pathType: Prefix
            backend:
              serviceName: web2
              servicePort: 8080