apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb2-rc
spec:
  replicas: 3
  selector:
    app: mywebsitetwo
   
  template:
   metadata:
    labels:
     app: mywebsitetwo
   spec:
    containers:
    - name: mywebsitetwo-container
      image: maha4iac/mahaonlinestore:2
      ports:
      - containerPort: 8080
